version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy_manager
    ports:
      - "8443:443"
    volumes:
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/ssl:/etc/nginx/ssl:ro
    restart: always
    networks:
      - proxy_manager_network

networks:
  proxy_manager_network:
    external: true
    name: proxy-manager_network
